version: '3.8'

networks:
  food_network:
    # Tạo mạng chung
    driver: bridge

services:
  food-nginx:
    image: nginx:latest
    container_name: food-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/domains.conf:/etc/nginx/conf.d/domains.conf
    depends_on:
      - food-web
      - food-api
    networks:
      - food_network
    restart: always # Tự khởi động khi restart laptop

  food-mongodb:
    image: mongo:latest
    container_name: food-mongodb
    ports:
      - "24017:27017"
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/initdb.sh:/root/mongodb/initdb.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - food_network
    restart: always

  food-api:
    build:
      context: ../food-api
      dockerfile: ../docker/api/Dockerfile
    container_name: food-api
    ports:
      - "8002:8002"
    volumes:
      - ../food-api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://admin:admin@cluster0.hoqsvah.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 # Sửa đúng format user:pass
    depends_on:
      - food-mongodb
    networks:
      - food_network
    restart: always

  food-web:
    build:
      context: ../food-web
      dockerfile: ../docker/web/Dockerfile
    container_name: food-web
    ports:
      - "8001:8001"
    volumes:
      - ../food-web:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://food-api:8002 # Cập nhật URL API cho đúng Docker network
    depends_on:
      - food-api
    networks:
      - food_network
    restart: always

  ai-service:
    build:
      context: ../ai-service
      dockerfile: ../docker/ai/Dockerfile
    container_name: ai-service
    volumes:
      - ../ai-service:/usr/src/app # Mount code vào container
      - /usr/src/app/__pycache__/ # Xóa cache để reload nhanh
    ports:
      - "8003:8003"
    networks:
      - food_network
    restart: always
